export const INIT_EXERCISES_ACTION = 'EXERSICES::INIT_EXERCISES_ACTION';
export const FILTER_EXERCISES_ACTION = 'EXERSICES::FILTER_EXERCISES_ACTION';
export const SHOW_EXERSCISE_INFO_ACTION = 'EXERSICES::SHOW_EXERSCISE_INFO_ACTION';
